import type { Lang } from "./lang-context";

type L<T> = { en: T; pt: T };

export type ProjectRaw = {
  slug: string;
  name: string;
  status: "prod" | "internal" | "wip";
  stack: string[];
  url?: string;
  role: L<string>;
  blurb: L<string>;
  metric: L<string>;
};

export type Project = {
  slug: string;
  name: string;
  status: "prod" | "internal" | "wip";
  stack: string[];
  url?: string;
  role: string;
  blurb: string;
  metric: string;
};

const projectsRaw: ProjectRaw[] = [
  {
    slug: "dashboard-oficial",
    name: "dashboard-oficial",
    status: "prod",
    stack: ["Next.js 16", "Supabase", "Claude Code", "Vercel"],
    role: {
      en: "Automated executive BI",
      pt: "BI executivo automatizado",
    },
    blurb: {
      en: "Versioned Next.js dashboard reading straight from the database, replacing fragmented manual reports. Built side-by-side with Claude Code, continuous deploy on Vercel, served from materialized views.",
      pt: "Dashboard Next.js versionado puxando direto do banco, no lugar de relatórios manuais fragmentados. Construído em par com Claude Code, deploy contínuo na Vercel, leitura via views materializadas.",
    },
    metric: {
      en: "near-instant load · daily revalidate · zero client-side queries",
      pt: "carregamento quase instantâneo · revalidate diário · zero query no client",
    },
  },
  {
    slug: "agents-console",
    name: "agents-console",
    status: "prod",
    stack: ["Next.js", "Supabase Auth", "Claude API"],
    role: { en: "Agents operations console", pt: "Console de operações dos agentes" },
    blurb: {
      en: "Operations dashboard for monitoring agent runs and overall health. Per-run insights generated by Claude on demand.",
      pt: "Painel de operações para acompanhar runs dos agentes e saúde geral. Insights por run gerados via Claude sob demanda.",
    },
    metric: {
      en: "restricted auth · 4 tabs · in prod since 2026-04",
      pt: "auth restrita · 4 tabs · em prod desde 2026-04",
    },
  },
  {
    slug: "monday-agent",
    name: "monday-agent",
    status: "prod",
    stack: ["Next.js", "Voyage", "Claude", "Supabase"],
    role: { en: "Conversational agent · Monday.com", pt: "Agente conversacional · Monday.com" },
    blurb: {
      en: "Talks about any item in a Monday board. RAG via Voyage embeddings, context assembled on the fly, streaming answers.",
      pt: "Conversa sobre qualquer item de um board do Monday. RAG via Voyage embeddings, contexto montado on-the-fly, resposta em streaming.",
    },
    metric: {
      en: "spark-monday-agent.vercel.app · live",
      pt: "spark-monday-agent.vercel.app · live",
    },
  },
  {
    slug: "ga4-agent",
    name: "ga4-agent",
    status: "internal",
    stack: ["Next.js", "GA4 API", "Claude"],
    role: { en: "Conversational agent · GA4", pt: "Agente conversacional · GA4" },
    blurb: {
      en: "Queries GA4 in natural language with drill-down and on-demand charts. Analytics agent.",
      pt: "Consulta GA4 em linguagem natural com drill-down e gráficos gerados sob demanda. Agente de análise.",
    },
    metric: {
      en: "spark-ga4-agent-ashy.vercel.app · live",
      pt: "spark-ga4-agent-ashy.vercel.app · live",
    },
  },
  {
    slug: "ai-hub",
    name: "ai-hub",
    status: "internal",
    stack: ["Next.js", "pgvector", "Voyage", "MCP"],
    role: { en: "RAG memory layer", pt: "Camada de memória RAG" },
    blurb: {
      en: "RAG memory layer exposing context to any AI client over REST/MCP. Continuous indexing of design docs, decisions and project notes.",
      pt: "Camada de memória RAG que expõe contexto pra qualquer cliente IA via REST/MCP. Indexação contínua de design docs, decisões e notas de projeto.",
    },
    metric: {
      en: "pgvector · Voyage v3 · MCP server",
      pt: "pgvector · Voyage v3 · MCP server",
    },
  },
  {
    slug: "spark-topologies",
    name: "spark-topologies",
    status: "prod",
    stack: ["R3F", "MediaPipe", "Voyage"],
    role: { en: "3D second-brain map", pt: "Mapa 3D do segundo cérebro" },
    blurb: {
      en: "Entire vault rendered in 3D. Voyage embeddings drive each node's position; MediaPipe hand-tracking lets you navigate by gesture.",
      pt: "Vault inteiro renderizado em 3D. Embeddings Voyage geram a posição de cada nó; hand-tracking via MediaPipe permite navegar por gesto.",
    },
    metric: {
      en: "spark-topologies.vercel.app · live · R3F",
      pt: "spark-topologies.vercel.app · live · R3F",
    },
  },
  {
    slug: "ds-lab",
    name: "ds-lab",
    status: "prod",
    stack: ["Next.js", "TypeScript"],
    role: { en: "Data science models showcase", pt: "Showcase dos modelos de DS" },
    blurb: {
      en: "Public site for the models: lead scoring, propensity-to-buy, churn shield, ltv prediction, roi predictor, creator segmentation, trend arbitrage radar.",
      pt: "Site público dos modelos: lead scoring, propensity-to-buy, churn shield, ltv prediction, roi predictor, creator segmentation, trend arbitrage radar.",
    },
    metric: {
      en: "spark-data-science-lab-indol.vercel.app · 7 models cataloged",
      pt: "spark-data-science-lab-indol.vercel.app · 7 modelos catalogados",
    },
  },
  {
    slug: "spark-ml",
    name: "spark-ml",
    status: "wip",
    stack: ["Python", "uv", "dbt", "Supabase"],
    role: { en: "ML monorepo", pt: "ML monorepo" },
    blurb: {
      en: "Single Python repo for every model. uv + Python 3.11, dbt for feature engineering, Supabase as the data plane.",
      pt: "Repositório único Python para todos os modelos. uv + Python 3.11, dbt para feature engineering, Supabase como data plane.",
    },
    metric: {
      en: "lead scoring is the first model · uv lockfile · dbt build in CI",
      pt: "lead scoring é o primeiro modelo · uv lockfile · CI dbt build",
    },
  },
  {
    slug: "spark-growth",
    name: "spark-growth",
    status: "wip",
    stack: ["Next.js", "Supabase"],
    role: { en: "Growth experiment tracker", pt: "Tracker de experimentos de growth" },
    blurb: {
      en: "Every growth move (video, post, live, LP change) becomes a trackable experiment with hypothesis, NSM and decision. Bullseye + ICE framework.",
      pt: "Cada ação de growth (vídeo, post, live, mudança de LP) vira experimento rastreável com hipótese, NSM e decisão. Framework Bullseye + ICE.",
    },
    metric: {
      en: "discovery · architecture defined",
      pt: "discovery · arquitetura definida",
    },
  },
  {
    slug: "lead-scoring",
    name: "lead-scoring",
    status: "wip",
    stack: ["Python", "scikit-learn", "dbt"],
    role: { en: "Predictive scoring model", pt: "Modelo preditivo · scoring" },
    blurb: {
      en: "Prioritizes leads with the highest historical conversion. Trained on a consolidated dataset, nightly rescore.",
      pt: "Prioriza leads de maior conversão histórica. Treinado sobre dataset consolidado, reescore noturno.",
    },
    metric: {
      en: "first model in spark-ml CI",
      pt: "primeiro modelo do spark-ml em ci",
    },
  },
  {
    slug: "hermes-site",
    name: "hermes-site",
    status: "prod",
    stack: ["Next.js", "Tailwind"],
    role: { en: "Agents showcase", pt: "Showcase dos agentes" },
    blurb: {
      en: "Showcase page for the 6 Hermes agents. Minimalist cyberpunk layout.",
      pt: "Página de apresentação dos 6 agentes Hermes. Layout cyberpunk minimalista.",
    },
    metric: {
      en: "Next.js 16 · local port 3004",
      pt: "Next.js 16 · porta local 3004",
    },
  },
];

export function getProjects(lang: Lang): Project[] {
  return projectsRaw.map((p) => ({
    slug: p.slug,
    name: p.name,
    status: p.status,
    stack: p.stack,
    url: p.url,
    role: p.role[lang],
    blurb: p.blurb[lang],
    metric: p.metric[lang],
  }));
}

export const projectSlugs = projectsRaw.map((p) => p.slug);

// ───────── Experience ─────────

export type RoleBlock = {
  company: string;
  role: string;
  period: string;
  current: boolean;
  summary: string;
  pillars: { slug: string; title: string; body: string }[];
};

export function getExperience(lang: Lang): RoleBlock[] {
  return [
    {
      company: "Spark MAXX",
      role: "Data Strategy & Analytics Coordinator",
      period: lang === "en" ? "2026-03 → present" : "2026-03 → atual",
      current: true,
      summary:
        lang === "en"
          ? "I coordinate BI, automation and LLM agents for the operation. The throughline: take manual analytics flows onto a versioned, auditable stack with AI in the loop."
          : "Coordeno BI, automação e agentes LLM da operação. O fio condutor: levar fluxos analíticos manuais pra um stack versionado, auditável, com IA no loop.",
      pillars: [
        {
          slug: "dashboard",
          title:
            lang === "en"
              ? "Official dashboard · fully automated"
              : "Dashboard oficial · automação completa",
          body:
            lang === "en"
              ? "Built side-by-side with Claude Code. Versioned Next.js dashboard pulling straight from the database, with scheduled revalidate and view-based reads. Continuous deploy on Vercel."
              : "Construído em par com Claude Code. Dashboard Next.js versionado, puxando direto do banco, com revalidate programado e leitura via views. Deploy contínuo na Vercel.",
        },
        {
          slug: "agents",
          title:
            lang === "en"
              ? "AI agents · GA4, Monday and what's next"
              : "Agentes de IA · GA4, Monday e o radar",
          body:
            lang === "en"
              ? "In production: GA4 agent (conversational analytics), Monday agent (RAG over boards), messaging agents with model-gated routing. On the radar: growth, product and sales agents."
              : "Em produção: agente GA4 (analytics conversacional), agente Monday (RAG sobre boards), agentes de messaging com roteamento model-gated. No radar: agente de growth, agente de produto, agente comercial.",
        },
        {
          slug: "automation",
          title:
            lang === "en"
              ? "AI & automation · from operational to analytical"
              : "IA & automação · do operacional ao analítico",
          body:
            lang === "en"
              ? "n8n pipelines for conditional routing, event-driven CRM integrations, idempotent webhooks. Everything passes through an explicit gate from another model before touching a critical system."
              : "Pipelines n8n para roteamento condicional, integrações event-driven com CRMs, webhooks idempotentes. Tudo passa por gate explícito de outro modelo antes de tocar sistema crítico.",
        },
        {
          slug: "ds-growth",
          title:
            lang === "en"
              ? "Data science & growth"
              : "Data science & growth",
          body:
            lang === "en"
              ? "Predictive models: lead scoring, propensity-to-buy, churn shield, LTV, ROI predictor. Growth framework with trackable experiments, hypothesis-NSM-decision. Stack in a Python monorepo (spark-ml) with dbt."
              : "Modelos preditivos: lead scoring, propensão a compra, churn shield, LTV, ROI predictor. Framework de growth com experimentos rastreáveis, hipótese-NSM-decisão. Stack em monorepo Python (spark-ml) com dbt.",
        },
      ],
    },
    {
      company: "Growth Leaders Academy",
      role: "Full-Stack Automation Developer",
      period: lang === "en" ? "Jun 2025 — Oct 2025" : "Jun 2025 — Out 2025",
      current: false,
      summary:
        lang === "en"
          ? "Automation ecosystems for Growth Ops. APIs, ETL, data analysis, conversion optimization."
          : "Ecossistemas de automação para Growth Ops. APIs, ETL, análise de dados, otimização de conversão.",
      pillars: [
        {
          slug: "event-orchestrator",
          title: "Event Registration Orchestrator",
          body:
            lang === "en"
              ? "n8n with Webhook Listener + base validation + synchronous feedback loop for instant confirmation under high volume."
              : "n8n com Webhook Listener + validação de base + feedback loop síncrono para confirmação imediata em alto volume.",
        },
        {
          slug: "revenue-recovery",
          title: "Real-Time Revenue Recovery",
          body:
            lang === "en"
              ? "Event-driven architecture: gateway monitoring → smart wait → personalized message dispatch to recover abandonments."
              : "Arquitetura event-driven: monitoramento de gateway → wait inteligente → disparo de mensagem personalizada para recuperar abandonos.",
        },
      ],
    },
  ];
}

// ───────── Education ─────────

export type EducationItem = {
  institution: string;
  course: string;
  period: string;
  note: string;
  ongoing: boolean;
};

export function getEducation(lang: Lang): EducationItem[] {
  return [
    {
      institution: "Universidade Anhembi Morumbi",
      course:
        lang === "en"
          ? "Postgrad · Cloud & Edge Computing"
          : "Pós-graduação · Cloud & Edge Computing",
      period: lang === "en" ? "ongoing" : "em curso",
      ongoing: true,
      note:
        lang === "en"
          ? "distributed computing, sub-second latency, edge runtimes."
          : "computação distribuída, latência sub-segundo, edge runtimes.",
    },
    {
      institution: "Universidade Nove de Julho — UNINOVE",
      course:
        lang === "en"
          ? "Associate Degree · Data Science"
          : "Tecnólogo · Ciência de Dados",
      period: lang === "en" ? "completed" : "concluído",
      ongoing: false,
      note:
        lang === "en"
          ? "statistics, predictive modeling, ML and data engineering fundamentals."
          : "estatística, modelagem preditiva, fundamentos de ML e engenharia de dados.",
    },
  ];
}
